version: 2

sources:
  - name: raw_sap_adw
    schema: raw_sap_adw
    loaded_at_field: cast(ind_extraction_date as timestamp)
    tables:
      - name: "customer"
        description: "Tabela com a relação de clientes."
        columns:
          - name: customerid
            tests:
              - unique
              - not_null
      - name: "salesorderdetail"
        description: "Tabela com a relação de todos os pedidos de venda e seus itens."
        columns:
          - name: salesorderid
            tests:
              - not_null
          - name: salesorderdetailid
            tests:
              - unique
              - not_null
      - name: "store"
        description: "Tabela com a relação das lojas revendedoras."
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: "salesorderheadersalesreason"
        description: "Tabela de registro dos pedidos e motivos de venda."
        columns:
          - name: salesreasonid
            tests:
              - not_null
          - name: salesorderid
            tests:
              - unique
              - not_null
      - name: "salesreason"
        description: "Tabela com a relação dos motivos de venda."
        columns:
          - name: salesreasonid
            tests:
              - unique
              - not_null
      - name: "salesorderheader"
        description: "Tabela com a relação de todos os pedidos de venda e seus itens."
        columns:
          - name: salesorderid
            tests:
              - unique
              - not_null
      - name: "salesterritory"
        description: "Tabela com a relação de todos os pedidos de venda e seus itens."
        columns:
          - name: territoryid
            tests:
              - unique
              - not_null
      - name: "department"
        description: "Tabela com a relação de departamentos."
        columns:
          - name: departmentid
            tests:
              - unique
              - not_null
      - name: "employee"
        description: "Tabela com a relação de colaboradores."
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: "purchaseorderdetail"
        description: "Tabela com o registro das ordens de compra e itens."
        columns:
          - name: purchaseorderdetailid
            tests:
              - unique
              - not_null
          - name: purchaseorderid
            tests:
              - not_null
      - name: "purchaseorderheader"
        description: "Tabela com o registro das ordens de compra."
        columns:
          - name: purchaseorderid
            tests:
              - unique
              - not_null
      - name: "vendor"
        description: "Tabela com a relação de fornecedores."
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: "product"
        description: "Tabela com a relação dos produtos."
        columns:
          - name: productid
            tests:
              - unique
              - not_null
      - name: "productcategory"
        description: "Tabela com a relação das categorias dos produtos."
        columns:
          - name: productcategoryid
            tests:
              - unique
              - not_null
      - name: "productmodel"
        description: "Tabela com a relação dos modelos dos produtos."
        columns:
          - name: productmodelid
            tests:
              - unique
              - not_null
      - name: "address"
        description: "Informações de endereço residencial para clientes, funcionários e fornecedores."
        columns:
          - name: addressid
            tests:
              - unique
              - not_null
      - name: "addresstype"
        description: "Tipos de endereços armazenados na tabela Address."
        columns:
          - name: addresstypeid
            tests:
              - unique
              - not_null
      - name: "businessentity"
        description: "Fonte da ID que conecta fornecedores, clientes e funcionários com endereço e informações de contato."
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: "businessentityaddress"
        description: "Tabela de referência cruzada mapeando clientes, fornecedores e funcionários para seus endereços."
        columns:
          - name: businessentityid
            tests:
              - not_null
          - name: addressid
            tests:
              - not_null
          - name: addresstypeid
            tests:
              - not_null
    
      - name: "countryregion"
        description: "Tabela de consulta contendo os códigos padrão ISO para países e regiões."
        columns:
          - name: countryregioncode
            tests:
              - unique
              - not_null
      - name: "person"
        description: "Seres humanos envolvidos com a AdventureWorks: funcionários, contatos de clientes e contatos de fornecedores."
        columns:
          - name: businessentityid
            tests:
              - unique
              - not_null
      - name: "stateprovince"
        description: "Tabela de consulta de estados e províncias."
        columns:
          - name: stateprovinceid
            tests:
              - unique
              - not_null